theme: jekyll-theme-cayman
title: EcoPoint
description: A gamified web-based waste management platform that integrates AI, Cloud Computing, and Computer Networks to deliver smart waste classification and real-time, reward-driven user engagement in a scalable system.